[package]
name = "no_738"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
wavelet_matrix = { path = "../../../crates/wavelet/wavelet_matrix" }