[workspace]
members = [
    "crates/internals/*",
    "crates/string/*",
    "crates/data_structure/*",
    "crates/algebra",
    "verify/yosupo/*",
    "verify/AOJ/*",
    "verify/AtCoder/*"
]
resolver = "2"