[workspace]
members = [
    "crates/internals/*",
    "crates/string/*",
    "crates/data_structure/*",
    "crates/algebra",
    "crates/modint/*",
    "crates/fps/*",
    "crates/flow/*",
    "crates/tree/*",
    "crates/misc/*",
    "crates/math/*",
    "crates/hash/*",
    "verify/yosupo/*",
    "verify/AOJ/*",
    "verify/AtCoder/*",
    "verify/yukicoder/*"
]
resolver = "2"