[workspace]
members = [
    "crates/internals/*",
    "crates/string/*",
    "crates/data_structure/*",
    "crates/algebra",
    "crates/modint/*",
    "crates/fps/*",
    "crates/flow/*",
    "verify/yosupo/*",
    "verify/AOJ/*",
    "verify/AtCoder/*",
    "verify/yukicoder/*"
]
resolver = "2"