#!/bin/sh

# Example of pre-commit hook in the git repository.

# Check if we are on the main branch
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "main" ]; then
    echo "Skipping pre-commit checks because we are not on the main branch."
    exit 0
fi

# run the tests
cargo check
if [ $? -ne 0 ]; then
  echo "cargo check failed"
  exit 1
fi

cargo fmt --all -- --check
if [ $? -ne 0 ]; then
  echo "cargo fmt failed"
  exit 1
fi

cargo clippy --lib -- -D warnings
if [ $? -ne 0 ]; then
  echo "cargo clippy failed"
  exit 1
fi

cargo test --all
if [ $? -ne 0 ]; then
  echo "cargo test failed"
  exit 1
fi