[package]
name = "frequency_table_of_tree_distance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
capture = { path = "../../../crates/tools/capture" }
centroid_decomposition = { path = "../../../crates/tree/centroid_decomposition" }
ntt = { path = "../../../crates/fps/ntt" }
static_modint = { path = "../../../crates/modint/static_modint" }