[package]
name = "vertex_set_path_composite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
algebra = { path = "../../../crates/algebra" }
segtree = { path = "../../../crates/data_structure/segtree" }
static_modint = { path = "../../../crates/modint/static_modint" }
hld = { path = "../../../crates/tree/hld" }