[package]
name = "abc328f"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
itertools = "=0.11.0"
algebra = { path = "../../../crates/algebra" }
potentialized_union_find = { path = "../../../crates/data_structure/potentialized_union_find" }