[package]
name = "unionfind_with_potential_non_commutative_group"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = { path = "../../../crates/algebra" }
static_modint = { path = "../../../crates/modint/static_modint" }
proconio = { version = "=0.4.5", features = ["derive"] }
potentialized_unionfind = { path = "../../../crates/data_structure/potentialized_unionfind" }
