[package]
name = "rect_add_point_get"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = { path = "../../algebra" }
internal_type_traits = { path = "../../internals/internal_type_traits" }