[package]
name = "point_add_rect_sum_wavelet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
algebra = { path = "../../../crates/algebra" }
wavelet_matrix_segtree = { path = "../../../crates/wavelet/wavelet_matrix_segtree" }