[package]
name = "inv_of_formal_power_series"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
fps_utils = { path = "../../../crates/fps/fps_utils"}
static_modint = { path = "../../../crates/modint/static_modint"}