[package]
name = "sum_of_floor_of_linear"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
floor_ceil_sum = { path = "../../../crates/math/floor_ceil_sum" }