[package]
name = "convolution_mod_1000000007_ntt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
static_modint = { path = "../../../crates/modint/static_modint" }
ntt_arbitrary_mod = { path = "../../../crates/fps/ntt_arbitrary_mod" }