[package]
name = "no_803"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
bit_matrix = { path = "../../../crates/math/bit_matrix" }
static_modint = { path = "../../../crates/modint/static_modint" }