[package]
name = "maxflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flow_cap_traits = { path = "../../internals/flow_cap_traits" }