[package]
name = "line_add_get_min"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
cht_offline = { path = "../../../crates/data_structure/cht_offline" }