[package]
name = "abc359g_centroid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
capture = { path = "../../../crates/utils/capture" }
centroid_decomposition = { path = "../../../crates/tree/centroid_decomposition" }
rustc-hash = "=1.1.0"