name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Set up Rust (1.70.0)
      run: |
        rustup set profile minimal
        rustup install 1.70.0
        rustup override set nightly

    - name: Run tests and generate docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: | 
        oj-verify all
        git switch main 
        cargo doc --lib --no-deps
        git switch gh-pages
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        cp -r ./target/doc cargo-doc
        git add -A
        git commit -m "update cargo doc"
        git push origin gh-pages
        git switch main